default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  
  username: postgres
  password: 123456
  host: localhost
  port: 5432

development:
  <<: *default
  database: automotora_development

test:
  <<: *default
  database: automotora_test

production:
  <<: *default
  database: automotora_production
  username: automotora
  password: <%= ENV["AUTOMOTORA_DATABASE_PASSWORD"] %>
